[package]
name = "rs-base-api"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-cors = "0.6.4"
actix-http = "3.4.0"
actix-identity = "0.6.0"
actix-service = "2.0.2"
actix-web = "4.3.1"
actix-web-actors = "4.2.0"
anyhow = "1.0.71"
async-stream = "0.3.5"
async-trait = "0.1.74"
bson = "2.7.0"
chrono = "0.4.26"
env_logger = "0.10.0"
envfile = "0.2.1"
envoption = "0.2.1"
failure = "0.1.8"
futures = "0.3.28"
futures-util = "0.3.28"
json = "0.12.4"
jsonwebtoken = "9.1.0"
log = "0.4.19"
mongodb = "2.7.0"
num_enum = "0.7.0"
pretty_env_logger = "0.5.0"
rc = "0.1.1"
rsntp = "3.0.2"
rust-argon2 = "2.0.0"
serde = { version = "1.0.166", features = ["derive"] }
smallvec = "1.10.0"
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-native-tls", "postgres" ] }
stoppable_thread = "0.2.1"
strum = "0.25.0"
strum_macros = "0.25.3"
thiserror = "1.0.40"
tokio = "1.33.0"
tracing = "0.1.37"

[dev-dependencies]
env_logger = "~0.10"
test-log = "~0.2"
